AWSTemplateFormatVersion: 2010-09-09
Description: This template provisions IAM groups, an automation user, and users with read-only permission

Parameters:
  UserPassword:
    Type: String
    Default: 'Password123!'
  
  MaxPasswordAge:
    Type: 'Number'
    Description: 'Maximum age for passwords'
    Default: 90
    ConstraintDescription: '(90-365 days)'
    MinValue: 90
    MaxValue: 365
  MinPasswordLength:
    Type: 'Number'
    Description: 'Minimum password length'
    Default: 10
    ConstraintDescription: '(8-128 characters)'
    MinValue: 8
    MaxValue: 128
  PasswordHistory:
    Type: 'Number'
    Description: 'Number of previous passwords to remember'
    Default: 3
    ConstraintDescription: '(1-24 passwords)'
    MinValue: 1
    MaxValue: 24
  RequireLowercaseChars:
    Type: 'String'
    Description: 'Require at least one lowercase character'
    Default: 'True'
    AllowedValues:
    - 'True'
    - 'False'
  RequireNumbers:
    Type: 'String'
    Description: 'Require at least one number'
    Default: 'True'
    AllowedValues:
    - 'True'
    - 'False'
  RequireSymbols:
    Type: 'String'
    Description: 'Require at least one symbol'
    Default: 'True'
    AllowedValues:
    - 'True'
    - 'False'
  RequireUppercaseChars:
    Type: 'String'
    Description: 'Require at least one uppercase character'
    Default: 'True'
    AllowedValues:
    - 'True'
    - 'False'

Resources:
  IAMPasswordPolicy:
    Type: 'Custom::IAMPolicyResource'
    Properties:
      ServiceToken: !GetAtt IAMPasswordPolicyResource.Arn
      Region: !Ref "AWS::Region"
      Policies:
      - PolicyName: GetFunctionConfigPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: 'Allow'
            Action:
            - 'lambda:GetFunctionConfiguration'
            Resource: '*'

  IAMPasswordPolicyResource:
    Type: "AWS::Lambda::Function"
    Properties:
      Runtime: python3.6
      Handler: index.lambda_handler
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt IAMPasswordPolicyResourceExecutionRole.Arn
      Code:
        ZipFile: !Sub |
          import boto3
          from botocore.exceptions import ClientError
          import json
          import cfnresponse
          iam = boto3.client("iam")
          # Lambda entry point
          def lambda_handler(event, context):
            if event['RequestType'] == 'Create' or event['RequestType'] == 'Update':
              res, reason = update_policy()
            elif event['RequestType'] == 'Delete':
              res, reason = delete_policy()
            else:
              res = False
              reason = "Unknown operation: " + event['RequestType']
            responseData = {}
            responseData['Reason'] = reason
            if res:
              cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
            else:
              cfnresponse.send(event, context, cfnresponse.FAILED, responseData)
          def update_policy():
            try:
              response = iam.update_account_password_policy(
                  AllowUsersToChangePassword=True,
                  HardExpiry=False,
                  MaxPasswordAge=${MaxPasswordAge},
                  MinimumPasswordLength=${MinPasswordLength},
                  RequireLowercaseCharacters=${RequireLowercaseChars},
                  RequireNumbers=${RequireNumbers},
                  RequireSymbols=${RequireSymbols},
                  RequireUppercaseCharacters=${RequireUppercaseChars},
                  PasswordReusePrevention=${PasswordHistory})
              return(True, response)
            except Exception as e:
              return (False, "Cannot update policy: " + str(e))
          def delete_policy():
            try:
              policy = iam.get_account_password_policy()
              response = iam.delete_account_password_policy()
              return (True, response)
            except Exception as e:
              return (False, "Cannot delete policy: " + str(e))

  IAMPasswordPolicyResourceExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: IAMPasswordCreatorPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: 'Allow'
            Action:
            - 'logs:CreateLogGroup'
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
            Resource: '*'
          - Effect: Allow
            Action:
              - iam:GetAccountPasswordPolicy
              - iam:UpdateAccountPasswordPolicy
              - iam:DeleteAccountPasswordPolicy
            Resource: "*"

  DeveloperGroup:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/CloudWatchLogsReadOnlyAccess'
      - 'arn:aws:iam::aws:policy/AmazonRDSReadOnlyAccess'
      - 'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'
      - 'arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess'
      - 'arn:aws:iam::aws:policy/AWSLambdaReadOnlyAccess'
      - 'arn:aws:iam::aws:policy/IAMReadOnlyAccess'

  AutomationPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: AutomationPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: DeployCFN
          Effect: Allow
          Action:
            - 'cloudformation:*'
          Resource:
            - '*'
        - Sid: PreventCFNDeletion
          Effect: Deny
          Action:
            - 'cloudformation:DeleteStack'
          Resource:
            - '*'
        - Sid: UpdateUsers
          Effect: Allow
          Action:
            - 'iam:CreateRole'
            - 'iam:CreateUser'
            - 'iam:DetachRolePolicy'
            - 'iam:AttachRolePolicy'
            - 'iam:DeleteRole'
            - 'iam:DeleteRolePolicy'
            - 'iam:DeleteUser'
            - 'iam:GetRole'
            - 'iam:GetUser'
            - 'iam:PassRole'
            - 'iam:PutRolePolicy'
            - 'iam:GetRolePolicy'
            - 'iam:CreateServiceLinkedRole'
            - 'iam:UpdateLoginProfile'
            - 'iam:RemoveUserFromGroup'
            - 'iam:DeleteLoginProfile'
            - 'iam:ListAccessKeys'
            - 'lambda:CreateFunction'
            - 'lambda:DeleteFunction'
            - 'lambda:GetFunction'
            - 'lambda:GetFunctionConfiguration'
            - 'lambda:GetLayerVersion'
            - 'lambda:AddPermission'
            - 'lambda:RemovePermission'
            - 'lambda:PublishLayerVersion'
            - 'lambda:UpdateFunctionCode'
            - 'lambda:ListTags'
            - 'lambda:TagResource'
            - 'lambda:UntagResource'
            - 'lambda:UpdateFunctionConfiguration'
          Resource:
            - '*'
      Groups:
        - !Ref AutomationGroup 

  AutomationGroup:
    Type: AWS::IAM::Group        

  AutomationUser:
    Type: AWS::IAM::User
    Properties:
      UserName: automation@maxgala.com
      LoginProfile:
        Password:
          Ref: UserPassword
        PasswordResetRequired: true
      Groups:
        - !Ref AutomationGroup

  SalehBakhit:
    Type: AWS::IAM::User
    Properties:
      UserName: saleh.bakhit@hotmail.com
      LoginProfile:
        Password:
          Ref: UserPassword
        PasswordResetRequired: true
      Groups:
        - !Ref DeveloperGroup

  AhmedHamodi:
    Type: AWS::IAM::User
    Properties:
      UserName: ahmed.r.hamodi@gmail.com
      LoginProfile:
        Password:
          Ref: UserPassword
        PasswordResetRequired: true
      Groups:
        - !Ref DeveloperGroup

  ArsalanRana:
    Type: AWS::IAM::User
    Properties:
      UserName: arsalan.rana@maxgala.com
      LoginProfile:
        Password:
          Ref: UserPassword
        PasswordResetRequired: true
      Groups:
        - !Ref DeveloperGroup

  TayyabTanveer:
    Type: AWS::IAM::User
    Properties:
      UserName: tayyaabtanveer@gmail.com
      LoginProfile:
        Password:
          Ref: UserPassword
        PasswordResetRequired: true
      Groups:
        - !Ref DeveloperGroup

  ShehryarSuleman:
    Type: AWS::IAM::User
    Properties:
      UserName: shehryarsuleman@gmail.com
      LoginProfile:
        Password:
          Ref: UserPassword
        PasswordResetRequired: true
      Groups:
        - !Ref DeveloperGroup

  NabaSiddiqui:
    Type: AWS::IAM::User
    Properties:
      UserName: naba@poketapp.com
      LoginProfile:
        Password:
          Ref: UserPassword
        PasswordResetRequired: true
      Groups:
        - !Ref DeveloperGroup

  HafsaZahid:
    Type: AWS::IAM::User
    Properties:
      UserName: hafsabzahid@gmail.com
      LoginProfile:
        Password:
          Ref: UserPassword
        PasswordResetRequired: true
      Groups:
        - !Ref DeveloperGroup

  AhmedJamal:
    Type: AWS::IAM::User
    Properties:
      UserName: ahmedjamal0208@gmail.com
      LoginProfile:
        Password:
          Ref: UserPassword
        PasswordResetRequired: true
      Groups:
        - !Ref DeveloperGroup

  RizTaha:
    Type: AWS::IAM::User
    Properties:
      UserName: riztaha@gmail.com
      LoginProfile:
        Password:
          Ref: UserPassword
        PasswordResetRequired: true
      Groups:
        - !Ref DeveloperGroup

  KashifSiddiqui:
    Type: AWS::IAM::User
    Properties:
      UserName: kashif89@gmail.com
      LoginProfile:
        Password:
          Ref: UserPassword
        PasswordResetRequired: true
      Groups:
        - !Ref DeveloperGroup