AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template provisions an S3 bucket to store resumes and cover letters.'

Parameters:
  S3BucketName:
    Type: String
    Default: max-aspire-profile
    Description: Name of S3 bucket
	
Resources:
  ProfileBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: 'Delete'
    Metadata:
      Comment: 'Bucket to store resumes and cover letters'
    Properties:
      AccessControl: 'Private'
      BucketName: !Ref S3BucketName
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls : true
        BlockPublicPolicy : true
        IgnorePublicAcls : true
        RestrictPublicBuckets : true
      AccelerateConfiguration:
        AccelerationStatus: Enabled
      VersioningConfiguration:
        Status: Enabled

Outputs:
  S3BucketName:
    Description: 'Bucket name'
    Value: !Ref S3BucketName
	