---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template provisions a certificate for *.aspire.maxgala.com domain'

Parameters:
  AspireApiDomainName:
    Type: String
    Default: '*.aspire.maxgala.com'
    Description: Domain name

Resources:
  AspireApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref AspireApiDomainName
      DomainValidationOptions: 
        - DomainName: !Ref AspireApiDomainName
          ValidationDomain: maxgala.com
      ValidationMethod: DNS

Outputs:
  CertificateArn:
    Description: 'Certificate ARN'
    Value: !Ref AspireApiCertificate